(menu-bar-mode -1)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(setq inhibit-startup-message t)
(setq make-backup-files nil)
(global-display-line-numbers-mode t)
(setq browse-url-browser-function 'browse-url-chromium)
